import { Component, Input, OnInit, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from '@angular/forms';
import { PluginParam } from '../../services/plugin.service';
import { TextControlComponent } from '../controls/text-control/text-control.component';
import { NumberControlComponent } from '../controls/number-control/number-control.component';
import { BooleanControlComponent } from '../controls/boolean-control/boolean-control.component';
import { RangeControlComponent } from '../controls/range-control/range-control.component';
import { FileControlComponent } from '../controls/file-control/file-control.component';

@Component({
  selector: 'app-dynamic-form',
  standalone: true,
  imports: [
    CommonModule, ReactiveFormsModule,
    TextControlComponent, NumberControlComponent,
    BooleanControlComponent, RangeControlComponent,
    FileControlComponent
  ],
  template: `
    <form [formGroup]="form">
      <div *ngFor="let param of schema" class="form-group-wrapper">
        <app-text-control *ngIf="param.type === 'text'" [param]="param" [control]="getControl(param.key)"></app-text-control>
        <app-number-control *ngIf="param.type === 'number'" [param]="param" [control]="getControl(param.key)"></app-number-control>
        <app-boolean-control *ngIf="param.type === 'boolean'" [param]="param" [control]="getControl(param.key)"></app-boolean-control>
        <app-range-control *ngIf="param.type === 'range'" [param]="param" [control]="getControl(param.key)"></app-range-control>
        <app-file-control *ngIf="param.type === 'file'" [param]="param" [control]="getControl(param.key)"></app-file-control>
      </div>
    </form>
  `
})
export class DynamicFormComponent implements OnInit {
  @Input() schema: PluginParam[] = [];
  @Input() form!: FormGroup;

  ngOnInit() {
      // Form should be already generated by the parent (SidePanel)
  }

  getControl(key: string): FormControl {
    return this.form.get(key) as FormControl;
  }
}
